#pragma once

// DomLM version — AUTO-GENERATED by CMake from the single-source-of-truth
// <repo-root>/VERSION file. Do NOT edit by hand; bump VERSION and re-run
// CMake configuration instead.

#define DOMLM_VERSION_STRING "3.0.0"
#define DOMLM_VERSION_MAJOR 3
#define DOMLM_VERSION_MINOR 0
#define DOMLM_VERSION_PATCH 0
