#pragma once

// DomLM version — AUTO-GENERATED by CMake from the single-source-of-truth
// <repo-root>/VERSION file. Do NOT edit by hand; bump VERSION and re-run
// CMake configuration instead.

#define DOMLM_VERSION_STRING "2.1.0"
#define DOMLM_VERSION_MAJOR 2
#define DOMLM_VERSION_MINOR 1
#define DOMLM_VERSION_PATCH 0
